version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: avito
    volumes:
      - postgres-db:/var/lib/postgresql/data
  server:
    container_name: server
    #image: serverimage
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
volumes:
  postgres-db:
    